- hosts: "{{where}}"
  remote_user: "{{ remote_user | default('') }}"
  gather_facts: no
  become: true
  vars:
    docker_network_name: monitoring-network
    prometheus_volume_base: /home/yech/prom-volume

  tasks:
    - name: Create docker net
      docker_network:
        name: "{{ docker_network_name }}"
        state: present

    - name: Create prometheus base volume
      file:
        state: directory
        path: "{{ item }}"
        owner: 65534
        group: 65534
        mode: 644
      loop:
        - "{{ prometheus_volume_base }}/config"
        - "{{ prometheus_volume_base }}/data"

    - name: Copy Prometheus config file to volume
      copy:
        src: ./utils/prometheus.yaml
        dest: "{{ prometheus_volume_base }}/config"
        owner: 65534
        group: 65534
        mode: 644

    - name: Pull prometheus docker image
      docker_image:
        name: prom/prometheus:v2.22.0
        source: pull
        state: present

    - name: Run prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus:v2.22.0
        recreate: true
        restart_policy: always
        networks:
        - name: "{{ docker_network_name }}"
          aliases:
            - prometheus
        user: "root"
        volumes:
          - "{{ prometheus_volume_base }}/config/prometheus.yaml:/etc/prometheus/prometheus.yml"
          - "{{ prometheus_volume_base }}/data:/data"
        ports:
        - '9090:9090'