- hosts: all
  become: true
  vars:
    docker_network_name: monitoring-network

  tasks:
    - name: Pull prometheus docker image
      docker_image:
        name: prom/prometheus:v2.22.0
        source: pull
        state: present

    - name: Run prometheus
      docker_container:
        name: nodee-exporter
        image: prom/node-exporter:v1.0.0
        networks:
        - name: "{{ docker_network_name }}"
          aliases:
            - node-exporter
        volumes:
          - /sys:/host/sys:ro
          - /:/rootfs:ro
          - /proc:/host/proc:ro
          - /etc/hostname:/etc/nodename